apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  containers:
  - image: {{ .Values.imagename }}
    name: {{ .Values.name }}
    resources: {}
    ports:
      - containerPort: 80
        protocol: TCP
    imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
