apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  containers:
  - image: {{ .Values.imagename }}
    name: {{ .Values.name }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
