kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  lables:
    app.kubernetes.io/managed-by: Helm
    run: {{ .Values.name }}
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: Helm
    run: {{ .Values.name }}
