kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
    
